KusionStack/kube-utils

- .gitignore
- .golangci.yaml
- controller/mixin/mixin.go
- controller/mixin/mixin_test.go
- controller/mixin/webhook.go
- controller/mixin/webhook_test.go
- go.mod
- go.sum
- multicluster/help_test.go
- multicluster/manager.go
- multicluster/manager_test.go
- multicluster/multi_cluster_cache.go
- multicluster/multi_cluster_client.go
- multicluster/type.go
> feat: add mixin to simplify controller and webhook construction

- controller/workqueue/defaults.go
- controller/workqueue/defaults_test.go
- controller/workqueue/priority_queue_test.go
- go.mod
- metrics/priority_queue.go
> fix workqueue

- controller/workqueue/defaults.go
- controller/workqueue/defaults_test.go
- controller/workqueue/priority_queue_test.go
- [] N
re https://github.com/KusionStack/kube-utils/issues/11
```release-note
None
```
> get workqueue priority from namespace label

- .gitignore
- multicluster/manager.go
- multicluster/multi_cluster_cache.go
- multicluster/suite_test.go
> use NewCache from options to new Cache

- multicluster/clusterinfo/context.go
- multicluster/controller/controller.go
- multicluster/help.go
- multicluster/help_test.go
- multicluster/manager.go
- multicluster/manager_test.go
- multicluster/multi_cluster_cache.go
- multicluster/multi_cluster_client.go
- multicluster/suite_test.go
- multicluster/type.go
> refactor multicluster

- cache/cache.go
- cache/cache_test.go
- cache/client.go
- multicluster/manager_test.go
- multicluster/multi_cluster_cache.go
- multicluster/multi_cluster_client.go
- multicluster/suite_test.go
> Client | Cache supports Get & List without deepcopy

- multicluster/controller/controller.go
- multicluster/manager.go
- multicluster/manager_test.go
- multicluster/multi_cluster_client.go
- multicluster/suite_test.go
re https://github.com/KusionStack/kube-utils/issues/20
```release-note
None
```
> feat: add partial discovery client for multicluster manager

- .github/workflows/ci.yaml
- .licenserc.yaml
- Makefile
- cache/cache_test.go
- controller/mixin/webhook_test.go
- controller/workqueue/priority_queue.go
- controller/workqueue/suite_test.go
- multicluster/help_test.go
- multicluster/manager_test.go
- multicluster/multi_cluster_cache.go
re https://github.com/KusionStack/kube-utils/issues/21
```release-note
None
```
> fix failed actions

- Makefile
- cache/cache_test.go
- multicluster/manager_test.go
- multicluster/multi_cluster_client.go
- multicluster/suite_test.go
> feat: rewrite multicluster discovery interface

- controller/initializer/initializer.go
- controller/initializer/initializer_test.go
> feat: introduce support for modifying the flag name of the initializer

- .github/workflows/ci.yaml
> ci: fix secret scan check failed on main branch

- multicluster/clusterinfo/context.go
- multicluster/controller/controller.go
- multicluster/controller/test_cluster_provider.go
- multicluster/manager.go
- multicluster/manager_test.go
- multicluster/metrics/metrics.go
- multicluster/multi_cluster_cache.go
- multicluster/suite_test.go
fix https://github.com/KusionStack/kube-utils/issues/28
Supports different cluster management solutions when use multicluster.
```release-note
None
```
> multicluster supports different cluster management solutions

- controller/initializer/initializer.go
- controller/initializer/initializer_test.go
> feat(initializer): delete hidden option

- controller/initializer/initializer.go
> feat(initializer): log active initializers during setup

- Makefile
fix https://github.com/KusionStack/kube-utils/actions/runs/8414615751/job/23038556366
re https://github.com/kubernetes-sigs/controller-runtime/issues/2720
Fix a bug when use setup-envtest latest version.
```release-note
None
```
> fix: pin envtest version

- go.mod
> fix(go.mod): correct kusionstack/kube-api version in require

- resourcetopo/manager.go
- resourcetopo/node_storage.go
- resourcetopo/resourcetopo_utils_test.go
- resourcetopo/types.go
> refactor, resourcetopo informer

- multicluster/clusterprovider/config/karbour.go
- tools/cert-generator/generator/generator.go
- tools/cert-generator/option.go
> fix: rename karbour to karpor

- metrics/priority_queue.go
Show detail information of priority queue.
re https://github.com/kubernetes-sigs/controller-runtime/blob/v0.18.0/pkg/internal/controller/metrics/metrics.go#L51-L56
```release-note
None
```
> fix: metrics of priority queue

- multicluster/manager_test.go
- multicluster/multi_cluster_client.go
…icluster
fix https://github.com/KusionStack/kube-utils/issues/48
```release-note
None
```
> fix: lost cluster infomation when failed to update resources

- .golangci.yaml
- extracter/jsonpath.go
> fix: correct code according to lint suggestion

- extracter/jsonpath_test.go
- extracter/parser.go
> feat: add support for JSONPath input without curly braces

- client/key.go
> feat: add func to get object key string from client.Object and admission.Request

- condition/helper.go
- condition/helper_test.go
> feat: add condition helper

- controller/expectations/controller_expectation.go
- controller/expectations/controller_expectation_test.go
- controller/expectations/resourceversion_expactation.go
- controller/expectations/resourceversion_expectation_test.go
- controller/expectations/suit_test.go
> feat: add ControllerExpectation and ResourceVersionExpectation

- .golangci.yaml
- cache/cache.go
- cert/cert.go
- cert/error.go
- cert/fs.go
- client/util.go
- condition/helper.go
- controller/expectations/controller_expectation.go
- controller/history/revision_control.go
- controller/history/revision_control_test.go
- controller/history/revision_test.go
- controller/initializer/initializer.go
- controller/workqueue/priority_queue.go
- extractor/extractor_test.go
- metrics/client.go
- multicluster/clusterprovider/controller.go
- multicluster/metrics/metrics.go
- multicluster/multi_cluster_cache.go
- multicluster/multi_cluster_client.go
- resourcetopo/examples/base_example.go
- resourcetopo/manager.go
- resourcetopo/node_storage.go
- resourcetopo/resourcetopo_test.go
- resourcetopo/resourcetopo_utils_test.go
- resourcetopo/utils.go
- webhook/certmanager/manager.go
> ci(lint): add two more linters gocritic and errorlint

- multicluster/clusterinfo/context.go
to let external packages read clusterInfo without importing this package
```release-note
None
```
> feat: make clusterInfo a plain string type

- client/finalizer.go
- client/finalizer_test.go
> feat: add context to finalizer helper funcs

- resourcetopo/node_info.go
- resourcetopo/node_relation_utils.go
- resourcetopo/node_storage.go
- resourcetopo/node_topology_updater.go
- resourcetopo/resourcetopo_test.go
- resourcetopo/resourcetopo_utils_test.go
> add multi routine test suites and adjust node lock logic
